### ISSUE TITLE
Block instead of project

### ISSUE THREAD

**Issue by nucleardreamer** [richbayliss/balena-zerotier-gateway#2]
I think this project might benefit a lot more by being a `block` instead of a a project, for visibility on balena hub. One of the main reasons is that it's totally self contained, but more pragmatically because of the [balenaHub container repository](https://www.balena.io/blog/improving-device-image-management-workflow-balenaHub-Container-Registry/) we have out now. So possible flow could be something like:
- Publish this repo [as a block](https://www.balena.io/docs/learn/deploy/deploy-with-balena-button/#balenayml-configuration-file) (`type: sw.block` in the balena.yml)
- Setup the [deploy to balena](https://github.com/marketplace/actions/deploy-to-balena) github action
- Change `README` to point to `bh.cr` to pull the image that was generated with the previous release

I can also help out/do these things if needed!

**Comment by richbayliss** [comment]
@nucleardreamer it has been while since I looked at blocks, but my understanding was that blocks would make up a component in a wider application stack; like adding Wifi connect to an existing service.

This application is designed to act entirely as an exit gateway for a ZeroTier network so I don't know if the above description applies to it. But perhaps my understanding of blocks is wrong? If blocks are a better path then I am happy to go that route.

**Comment by richbayliss** [comment]
@nucleardreamer regarding the use of Deploy to Balena GH action - does it also handle updating the SemVer value in the `balena.yml` file? At the moment that would need to be manually updated in the PR, correct?
